document.write('<style type="text/css">');
document.write('.rainbow {');
document.write('  position: fixed;');
document.write('  z-index: 999999;');
document.write('  width: 100%;');
document.write('  height: 0.5%;');
document.write('  left:  0;');
document.write('}');
document.write('html {');
document.write('  padding-bottom: 3%;');
document.write('}');
document.write('#rainbow_red    { bottom: 2.50%; background: #FF0018; }');
document.write('#rainbow_orange { bottom: 2.00%; background: #FFA52C; }');
document.write('#rainbow_yellow { bottom: 1.50%; background: #FFFF41; }');
document.write('#rainbow_green  { bottom: 1.00%; background: #008018; }');
document.write('#rainbow_blue   { bottom: 0.50%; background: #0000F9; }');
document.write('#rainbow_violet { bottom: 0.00%; background: #86007D; }');
document.write('</style>');
document.write('<div id="rainbow_red"    class="rainbow"></div>');
document.write('<div id="rainbow_orange" class="rainbow"></div>');
document.write('<div id="rainbow_yellow" class="rainbow"></div>');
document.write('<div id="rainbow_green"  class="rainbow"></div>');
document.write('<div id="rainbow_blue"   class="rainbow"></div>');
document.write('<div id="rainbow_violet" class="rainbow"></div>');